name: AWS Secure AMI 

on:
  pull_request:
  push:
    branches: [main]

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} 
          # if you have/need it
          aws-region: us-east-1

      # Setup Mondoo
      - name: Install Mondoo Client
        shell: bash
        run: |
            echo Installing Mondoo Client...
            echo ${{ secrets.MONDOO_CLIENT_ACCOUNT }} | base64 -d > mondoo.json
            curl -sSL https://mondoo.com/install.sh | bash

      # Initialize Packer templates
      - name: Initialize Packer Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: init

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: aws-ubuntu2002.pkr.hcl

      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: aws-ubuntu2002.pkr.hcl
        env:
          PACKER_LOG: 1

      